version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: sketchscript
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sketchscript_network

  code-executor:
    build:
      context: ./server/docker/code-executor
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - sketchscript_network
    privileged: true

volumes:
  postgres_data:

networks:
  sketchscript_network:
    driver: bridge 